<spec> ::= <singlespec> | <singlespec> ; <spec>
<singlespec> ::= <sequence> | G(F( <goal> )) | G( <goal> ) | G(!( <goal> ) "|" ( <sequence> ))
<sequence> ::= F ( ( <goal> ) & ( X ( <sequence> ) ) ) | <goal> | X ( <sequence> )
<goal> ::= <literal> | !( <ngoal> ) | ( <literal> ) & ( <goal> ) | ( <literal> ) "|" ( <goal> )
<ngoal> ::= <literal> | ( <literal> ) & ( <goal> ) | ( <literal> ) "|" ( <goal> )